version: "3.7"
services:
  <project-name>:
    container_name: <project-name>
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run production
